/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortiz_sobrino_elena_di04_tarea.components;

/**
 *
 * @author elena
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    FramePlanificador planificador;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        panelInstrucciones = new javax.swing.JScrollPane();
        instruccionesTextArea = new javax.swing.JTextArea();
        jLabelIcon = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        plannerButton = new javax.swing.JMenu();
        plannerItem = new javax.swing.JMenuItem();
        accesibilidadButton = new javax.swing.JMenu();
        changeTheme = new javax.swing.JCheckBoxMenuItem();
        changeFontSize = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instrucciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14))); // NOI18N

        instruccionesTextArea.setEditable(false);
        instruccionesTextArea.setColumns(20);
        instruccionesTextArea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        instruccionesTextArea.setRows(5);
        instruccionesTextArea.setText("Planificador: \nuse el planificador para ejecutar los programas que desee a una fecha y hora\n determinados\n\nAccesibilidad: \nPermite editar configuraciones del programa como el tema o el \ntamaño de la fuente\n");
        panelInstrucciones.setViewportView(instruccionesTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(panelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortiz_sobrino_elena_di04_tarea/images/planner_icon.png"))); // NOI18N

        plannerButton.setText("Planificador");

        plannerItem.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        plannerItem.setText("Ver planificador...");
        plannerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plannerItemActionPerformed(evt);
            }
        });
        plannerButton.add(plannerItem);

        barraMenu.add(plannerButton);

        accesibilidadButton.setText("Accesibilidad");

        changeTheme.setSelected(true);
        changeTheme.setText("Cambiar temas...");
        changeTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeThemeActionPerformed(evt);
            }
        });
        accesibilidadButton.add(changeTheme);

        changeFontSize.setSelected(true);
        changeFontSize.setText("Cambiar tamaños...");
        changeFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontSizeActionPerformed(evt);
            }
        });
        accesibilidadButton.add(changeFontSize);

        barraMenu.add(accesibilidadButton);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeThemeActionPerformed
        new DialogoTema(this, true).setVisible(true);
    }//GEN-LAST:event_changeThemeActionPerformed

    private void plannerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plannerItemActionPerformed
       planificador =  new FramePlanificador();
       planificador.setVisible(true);
    }//GEN-LAST:event_plannerItemActionPerformed

    private void changeFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontSizeActionPerformed
         new DialogoFuentes(this, true).setVisible(true);
    }//GEN-LAST:event_changeFontSizeActionPerformed

    public FramePlanificador getPlanificador(){
        return this.planificador;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accesibilidadButton;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JCheckBoxMenuItem changeFontSize;
    private javax.swing.JCheckBoxMenuItem changeTheme;
    private javax.swing.JTextArea instruccionesTextArea;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane panelInstrucciones;
    private javax.swing.JMenu plannerButton;
    private javax.swing.JMenuItem plannerItem;
    // End of variables declaration//GEN-END:variables
}
