/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortiz_sobrino_elena_di04_tarea;

/**
 *
 * @author elena
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    FramePlanificador planificador;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        fontLabel = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        plannerButton = new javax.swing.JMenu();
        plannerItem = new javax.swing.JMenuItem();
        accesibilidadButton = new javax.swing.JMenu();
        changeTheme = new javax.swing.JCheckBoxMenuItem();
        changeFontSize = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fontLabel.setText("Cambiar fuentes");

        plannerButton.setText("Planificador");

        plannerItem.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        plannerItem.setText("Ver planificador...");
        plannerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plannerItemActionPerformed(evt);
            }
        });
        plannerButton.add(plannerItem);

        jMenuBar2.add(plannerButton);

        accesibilidadButton.setText("Accesibilidad");

        changeTheme.setSelected(true);
        changeTheme.setText("Cambiar temas...");
        changeTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeThemeActionPerformed(evt);
            }
        });
        accesibilidadButton.add(changeTheme);

        changeFontSize.setSelected(true);
        changeFontSize.setText("Cambiar tamaños...");
        changeFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontSizeActionPerformed(evt);
            }
        });
        accesibilidadButton.add(changeFontSize);

        jMenuBar2.add(accesibilidadButton);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(fontLabel)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(fontLabel)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeThemeActionPerformed
        new DialogoTema(this, true).setVisible(true);
    }//GEN-LAST:event_changeThemeActionPerformed

    private void plannerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plannerItemActionPerformed
       planificador =  new FramePlanificador();
       planificador.setVisible(true);
    }//GEN-LAST:event_plannerItemActionPerformed

    private void changeFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontSizeActionPerformed
         new DialogoFuentes(this, true).setVisible(true);
    }//GEN-LAST:event_changeFontSizeActionPerformed

    public FramePlanificador getPlanificador(){
        return this.planificador;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accesibilidadButton;
    private javax.swing.JCheckBoxMenuItem changeFontSize;
    private javax.swing.JCheckBoxMenuItem changeTheme;
    private javax.swing.JLabel fontLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu plannerButton;
    private javax.swing.JMenuItem plannerItem;
    // End of variables declaration//GEN-END:variables
}
